import { Inter } from "next/font/google";

const sfPro = Inter({
  variable: "--font-sf-pro",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${sfPro.variable} antialiased`}
        style={{ fontFamily: '-apple-system, BlinkMacSystemFont, "SF Pro Display", "SF Pro Text", system-ui, sans-serif' }}
      >
        {children}
      </body>
    </html>
  );
}